# Create an array to store 3 boolean values entered in by the user. 
# Print out YES if all the values are true and NO if at least one value is false. 
# Hint: Prompt the user to enter true or false, and accept those values using gets. 
# Since gets will give us back a string (instead of the boolean values we want) 
# use if statements to convert those strings to boolean values.

# arr_of_bool = []

# 3.times do 
#   print "Enter a boolean value (true or false): "
#   bool = gets.chomp.downcase
#     if bool == "true"
#       arr_of_bool << true
#     elsif bool == "false"
#       arr_of_bool << false
#     end
# end

# if arr_of_bool.include?(false)
#   print "NO"
# else
#   print "YES"
# end



# Create an array to store the following words: 
# firetruck, fire drill, fire hydrant, firefighter, fireproof, fire station, fire hose. 
# Then write code that uses the array to 
# print out truck, drill, hydrant, fighter, proof, station, hose 
# without modifying the original array.

# fire_words = ["firetruck", "fire drill", "fire hydrant", "firefighter", "fireproof", "fire station", "fire hose"]
# un_fire_words = []

# fire_words.each do |word|
#   # if it's two words, .split will create an array of two words. 
#   # eg. "fire drill".split would create ["fire", "drill"]
#   if word.split[1] != nil
#     un_fire_words << word.split[1]
#   else
#     # eg. "firetruck".split would create ["", "truck"]
#     un_fire_words << word.split("fire")[1]
#   end
# end

# print un_fire_words



# Create an array to store the amount of money spent on 4 people during the Holidays. 
# Have the user enter in the amount spent on each person. 
# Print the total spent on all the people. 
# Total money spent should be displayed with a dollar sign, decimal point, 
# and only 2 digits after the decimal.

# money_spent = []
# sum = 0

# i = 1
# 4.times do
#   print "Enter money spent by person #{i}: $"
#   sum += gets.chomp.to_f

#   i += 1
# end

# puts "Total money spent: $%.2f" % sum



# Create an array to store 5 random numbers 
# (between 1 and 10, including both 1 and 10) generated by the computer. 
# Print out the square of each of the elements in the array.

rand_num = Array.new(5) { rand(1..10) }

rand_num.each { |num| print "#{num ** 2} " }